<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
    <line>
      <![CDATA[Click to see Screen Image.]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Thu_Dec_26_09_51_58_IST_2019.jpg>ScreenImage</>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Thu_Dec_26_09_51_58_IST_2019.jpg><img src=Thu_Dec_26_09_51_58_IST_2019.jpg height=200 width=200></img></>]]>
    </line>
    <line>
      <![CDATA[Click to see Screen Image.]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Thu_Dec_26_09_52_48_IST_2019.jpg>ScreenImage</>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Thu_Dec_26_09_52_48_IST_2019.jpg><img src=Thu_Dec_26_09_52_48_IST_2019.jpg height=200 width=200></img></>]]>
    </line>
  </reporter-output>
  <suite name="PageObjectModel factories" duration-ms="131517" started-at="2019-12-26T09:50:39 IST" finished-at="2019-12-26T09:52:50 IST">
    <groups>
    </groups>
    <test name="SignInTest" duration-ms="37608" started-at="2019-12-26T09:50:39 IST" finished-at="2019-12-26T09:51:16 IST">
      <class name="com.w2a.testcases.SignInTest">
        <test-method status="PASS" signature="signInTest(java.util.Hashtable)[pri:0, instance:com.w2a.testcases.SignInTest@742ff096]" name="signInTest" duration-ms="21778" started-at="2019-12-26T09:50:39 IST" data-provider="dp" finished-at="2019-12-26T09:51:01 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Password_1234, Runmode=Y, username=mp_apr80@outlook.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signInTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.w2a.testcases.SignInTest@742ff096]" name="tearDown" is-config="true" duration-ms="863" started-at="2019-12-26T09:51:01 IST" finished-at="2019-12-26T09:51:02 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="signInTest(java.util.Hashtable)[pri:0, instance:com.w2a.testcases.SignInTest@742ff096]" name="signInTest" duration-ms="13851" started-at="2019-12-26T09:51:02 IST" data-provider="dp" finished-at="2019-12-26T09:51:16 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Password_1234, Runmode=Y, username=mp_apr81@outlook.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signInTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.w2a.testcases.SignInTest@742ff096]" name="tearDown" is-config="true" duration-ms="888" started-at="2019-12-26T09:51:16 IST" finished-at="2019-12-26T09:51:16 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.w2a.testcases.SignInTest -->
    </test> <!-- SignInTest -->
    <test name="FlightSearchTest" duration-ms="93880" started-at="2019-12-26T09:51:16 IST" finished-at="2019-12-26T09:52:50 IST">
      <class name="com.w2a.testcases.FlightSearchTest">
        <test-method status="FAIL" signature="flightSearchTest(java.util.Hashtable)[pri:0, instance:com.w2a.testcases.FlightSearchTest@5032714f]" name="flightSearchTest" duration-ms="41273" started-at="2019-12-26T09:51:17 IST" data-provider="dp" finished-at="2019-12-26T09:51:58 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{age=3.0, toDate=20/01/2020, fromDate=14/01/2020, Runmode=Y, toCity=Pune, India (PNQ-Lohegaon), fromCity=Delhi, India (DEL-Indira Gandhi Intl.)}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [6] but found [5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [6] but found [5]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:563)
at com.w2a.errorcollectors.ErrorCollector.assertEquals(ErrorCollector.java:38)
at com.w2a.errorcollectors.ErrorCollector.verifyEquals(ErrorCollector.java:102)
at com.w2a.testcases.FlightSearchTest.flightSearchTest(FlightSearchTest.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see Screen Image.]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Thu_Dec_26_09_51_58_IST_2019.jpg>ScreenImage</>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Thu_Dec_26_09_51_58_IST_2019.jpg><img src=Thu_Dec_26_09_51_58_IST_2019.jpg height=200 width=200></img></>]]>
            </line>
          </reporter-output>
        </test-method> <!-- flightSearchTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.w2a.testcases.FlightSearchTest@5032714f]" name="tearDown" is-config="true" duration-ms="909" started-at="2019-12-26T09:51:59 IST" finished-at="2019-12-26T09:52:00 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="flightSearchTest(java.util.Hashtable)[pri:0, instance:com.w2a.testcases.FlightSearchTest@5032714f]" name="flightSearchTest" duration-ms="47834" started-at="2019-12-26T09:52:00 IST" data-provider="dp" finished-at="2019-12-26T09:52:48 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{age=3.0, toDate=20/01/2020, fromDate=14/01/2020, Runmode=Y, toCity=Pune, India (PNQ-Lohegaon), fromCity=Bengaluru, India (BLR-Kempegowda Intl.)}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [6] but found [5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [6] but found [5]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:563)
at com.w2a.errorcollectors.ErrorCollector.assertEquals(ErrorCollector.java:38)
at com.w2a.errorcollectors.ErrorCollector.verifyEquals(ErrorCollector.java:102)
at com.w2a.testcases.FlightSearchTest.flightSearchTest(FlightSearchTest.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see Screen Image.]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Thu_Dec_26_09_52_48_IST_2019.jpg>ScreenImage</>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Thu_Dec_26_09_52_48_IST_2019.jpg><img src=Thu_Dec_26_09_52_48_IST_2019.jpg height=200 width=200></img></>]]>
            </line>
          </reporter-output>
        </test-method> <!-- flightSearchTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.w2a.testcases.FlightSearchTest@5032714f]" name="tearDown" is-config="true" duration-ms="907" started-at="2019-12-26T09:52:49 IST" finished-at="2019-12-26T09:52:50 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.w2a.testcases.FlightSearchTest -->
    </test> <!-- FlightSearchTest -->
  </suite> <!-- PageObjectModel factories -->
</testng-results>
